### ISSUE TITLE
Welcome to GitHub

### ISSUE THREAD

**Issue by githubteacher** [githubteacher/cloaked-octo-shame#1]
Please leave a comment below to be added to the repository

Bonus points for adding what you hope to learn the most of in these two days.

**Comment by dfarr** [comment]
first!

**Comment by dpdornseifer** [comment]
Great

**Comment by nirkoren** [comment]
Nir Koren

**Comment by githubstudent** [comment]
Please add me!

**Comment by geekflyer** [comment]
:santa: 
- branching strategies
- fancy history rewriting stuff (in particular squashing, reordering commits etc.), maybe repairing a mess with some cherry picks etc.
- thorough understanding of reflog and related commands

**Comment by benboeser** [comment]
:+1:

**Comment by b2m9** [comment]
+1

**Comment by gadimelamed** [comment]
cool!

**Comment by howarddierking** [comment]
add me please!

### learning goals
- more on internal details like refspecs
- history re-writing techniques

**Comment by recyard** [comment]
nice

**Comment by gruiz17** [comment]
:hankey:

**Comment by paschmann** [comment]
Become a reproducing octocat machine ;)

**Comment by matz3** [comment]
👍

**Comment by andfich** [comment]
thumbs-up

**Comment by casche** [comment]
keke.
1. Where did the Octocat come from? 
2. I would like to learn how to solve apocalyptic Git scenarios. Like the best practices for dealing with repositories with worst possible non-linear history, reverting prior commits etc.

**Comment by mlenkeit** [comment]
:+1:

**Comment by thojansen** [comment]
:+1:

**Comment by timoha** [comment]
#yolo #swag

**Comment by Lokenath** [comment]
GitHub is Awesome !!!
Wanna learn more !!

**Comment by rogerxu** [comment]
great!

**Comment by ghost** [comment]
hello

**Comment by saise200522** [comment]
Am here

**Comment by Colean128** [comment]
Can you Please add me!

**Comment by githubstudent** [comment]
Looks like everyone's added.
