### ISSUE TITLE
Could not resolve host: github.com with SAP-Network

### ISSUE THREAD

**Issue by gadimelamed** [githubteacher/cloaked-octo-shame#40]
Hi,

I'm connected to SAP Network via BIG-IP Edge-client.
on pull request I get an error:
Could not resolve host: github.com

What should I configure to be able to work with github.com while connected to SAP-Network?

Thanks,
Gadi

**Comment by andfich** [comment]
You can set the proxy in the git config:
git config [--global] http.proxy proxy:8080

**Comment by andfich** [comment]
... and you can unset the proxy with git config --global --unset http.proxy

**Comment by thojansen** [comment]
yepp, proxy.

```
git config http.proxy http://proxy:8080
git config https.proxy http://proxy:8080
```

**Comment by b2m9** [comment]
Maybe helpful: I wrote a little script to unset the proxy (my git global is with proxy) and I can unset the proxy with one single line

**Comment by gadimelamed** [comment]
@andfich Thanks!
@b2m9 I'll try to use git aliases for that

**Comment by githubteacher** [comment]
http://stackoverflow.com/questions/128035/how-do-i-pull-from-a-git-repository-through-an-http-proxy
