### ISSUE TITLE
Rewriting history

### ISSUE THREAD

**Issue by githubstudent** [githubteacher/cloaked-octo-shame#6]
@geekflyer From your comment [here](https://github.com/githubteacher/cloaked-octo-shame/issues/1#issuecomment-110087994):

> fancy history rewriting stuff (in particular squashing, reordering commits etc.), maybe repairing a mess with some cherry picks etc.

**Comment by casche** [comment]
:+1:

**Comment by Colean128** [comment]
:clap: Good ridddance!
