### ISSUE TITLE
Git Reference

### ISSUE THREAD

**Issue by casche** [githubteacher/cloaked-octo-shame#60]
Besides https://git-scm.com/book, does anyone have any recommendations for an 'advanced' Git Text?

**Comment by b2m9** [comment]
How about Github's website?
https://training.github.com/kit/advanced/

**Comment by githubstudent** [comment]
@casche Asking around right now...

**Comment by howarddierking** [comment]
big fan of http://shop.oreilly.com/product/0636920022862.do

**Comment by githubstudent** [comment]
@casche http://amzn.com/1449316387

**Comment by casche** [comment]
thanks :+1:
