### ISSUE TITLE
How to find a commit which contains a specific code snippet

### ISSUE THREAD

**Issue by geekflyer** [githubteacher/cloaked-octo-shame#63]
I want to find out how to find a commit which contains a specific code snippet, which was there in the past but has been removed already again.

E.g. Let's say I want to find the last commit which contained the statement `console.log('Hello World');`. (assuming that it's not there anymore in the current HEAD)

**Comment by githubstudent** [comment]
@geekflyer. This command will find diffs that introduce or remove an instance of `<string>`:

`git log -S <string>`

**Comment by geekflyer** [comment]
Thanks! Worked and I could find a specific commit a colleague back in Germany was asking me for :-)
