### ISSUE TITLE
Tips on Git Hooks

### ISSUE THREAD

**Issue by mlenkeit** [githubteacher/cloaked-octo-shame#66]
Is there anything that you would recommend (not) doing via git hooks?

**Comment by githubstudent** [comment]
@mlenkeit Are we talking client-side or server-side hooks?

**Comment by mlenkeit** [comment]
I was thinking about client-side, but talking about server-side might also be helpful.
Edit: if server-side hooks is the same as web hooks, then this has already been covered :+1:

**Comment by mlenkeit** [comment]
> Avoid expensive operations in client-side hooks
> GitHub itself currently doesn't support server-side hooks
